# Generated by Django 4.2.2 on 2024-05-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
